### ISSUE TITLE
Test: add unit test using Jest.js

### ISSUE THREAD

**Issue by jofftiquez** [trinly01/TrinDB#1]
It would be awesome if we add a few test suites using Jest.

Assign it to me if you agreed. :)

**Comment by trinly01** [comment]
> It would be awesome if we add a few test suites using Jest.
> 
> Assign it to me if you agreed. :)

That's great! Contributors are welcome ❤️

**Comment by trinly01** [comment]
Please convert it as a pull request. Will love to merge it. ❤️

**Comment by trinly01** [comment]
> It would be awesome if we add a few test suites using Jest.
> 
> Assign it to me if you agreed. :)

Please convert it as a pull request. Will love to merge it. ❤️

**Comment by jofftiquez** [comment]
Noted @trinly01 thanks.
