### ISSUE TITLE
Chore: Add linter

### ISSUE THREAD

**Issue by jofftiquez** [trinly01/TrinDB#2]
Let's add ESLint maybe, let me know if you think it's necessary.

**Comment by trinly01** [comment]
> Let's add ESLint maybe, let me know if you think it's necessary.

I will close it for now joff, since it is not a priority.
My initial plans are the following
1. Authentication
2. ORM
3. Admin UI
4. Web sockets
5. Client-side SDK

**Comment by jofftiquez** [comment]
Noted @trinly01 thanks.
